version: 0.2

phases:
  pre_build:
    commands:
      - cd frontend
      - npm i -g npm && npm ci
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: frontend/build
